server:
  port: ${APP_PORT:8080}

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DB:0}

app:
  session:
    ttl: ${APP_USER_SESSION_TTL:3600}
  reactions:
    ttl: ${APP_LIKE_TTL:60}
  cassandra:
    hosts: ${CASSANDRA_HOSTS:localhost}
    port: ${CASSANDRA_PORT:9042}
    username: ${CASSANDRA_USERNAME:}
    password: ${CASSANDRA_PASSWORD:}
    keyspace: ${CASSANDRA_KEYSPACE:testkeyspace}
    consistency: ${CASSANDRA_CONSISTENCY:ONE}
    local-datacenter: datacenter1
  mongodb:
    database: ${MONGODB_EVENTHUB_DATABASE:${MONGODB_DATABASE:eventhub}}
    user: ${MONGODB_USER:}
    password: ${MONGODB_PASSWORD:}
    host: ${MONGODB_HOST:localhost}
    port: ${MONGODB_PORT:27017}
